# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  -openjdk11
# используем режим обычного пользователя для сборки проекта.

services:
  - postgresql

before_install:
  - psql -c 'CREATE DATABASE tracker;' -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)


addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
env:
  global:
    - PGPORT=5434

# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - andykirill@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
