# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
jdk:
  - openjdk11
# используем режим обычного пользователя для сборки проекта.
sudo: false

# for codecov.io
env:
  global:
    - CODECOV_TOKEN="8786a5bf-2e1f-48b8-8875-51ea34272f91"

services:
  - postgresql

before_install:
  - psql -c 'CREATE DATABASE tracker;' -U postgres
  - psql -U postgres -p -D tracker < .\db\create.sql

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - andykirill@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
